### ISSUE TITLE
Script Syntax Error on FrSky Taranis

### ISSUE THREAD

**Issue by agmorpheus** [rotorflight/rotorflight-lua-scripts#64]
Hello,

when I try to start the script, I get an error "Script syntax Error". The script compiling went throuth without problems.
I also removed almost every other lua script in case it is a memory issue, but also no success.

Thanks
Andre

**Comment by egonl** [comment]
Could you be more specific? What did you download (master or release), and what OS and version (EdgeTX or OpenTX)?

**Comment by agmorpheus** [comment]
I have downloaded the release version. I use OpenTX latest version (2.3.15).
Today i also formatted the SD card and copied the latest SD content. But again no success.
After compiling i checked the generated luac files. What I noticed that the QUICK.luac was empty, all other files had a least a size of 1 KB.

**Comment by agmorpheus** [comment]
Some more information:

- I use the R-XSR receiver flashed with 2.1.0
- meanwhile I also tried the script from the master. It also does not work

**Comment by egonl** [comment]
Which Taranis do you have?

Op vr 30 aug. 2024 12:00 schreef agmorpheus ***@***.***>:

**Comment by egonl** [comment]
Strange. One of my development transmitters is the Taranis Q X7 with OpenTX 2.3.15 as well. No issues there.

I'll close this issue, but I'll keep it in mind in case another X9D+ user encounters this error.
