### ISSUE TITLE
Luascript x20s ethos not work

### ISSUE THREAD

**Issue by eliasmoby** [rotorflight/rotorflight-lua-scripts#67]
When i use RF2 luascript the message validating api version freeze the radio lua script and dont work

Im.using tdmx receiver with f.port and ethis 1.5.15 version

Regards in advace

**Comment by egonl** [comment]
Just pushed the latest version to master, could you give that a try?

**Comment by eliasmoby** [comment]
Wich version is ?Enviado desde mi Samsung Mobile de Telcel
-------- Mensaje original --------De: egonl ***@***.***> Fecha: 24/9/2024  3:17 p. m.  (GMT-06:00) A: rotorflight/rotorflight-lua-scripts ***@***.***> CC: eliasmoby ***@***.***>, Author ***@***.***> Asunto: Re: [rotorflight/rotorflight-lua-scripts] Luascript x20s ethos not work (Issue #67) 
Just pushed the latest version to master, could you give that a try?

**Comment by egonl** [comment]
You can download the latest version here: https://github.com/rotorflight/rotorflight-lua-ethos/archive/refs/heads/master.zip

**Comment by eliasmoby** [comment]
Still not working!
![17272149169164150276621195003525](https://github.com/user-attachments/assets/5d7fbadb-0a39-4617-acfc-581f13992235)
![20240924_155336](https://github.com/user-attachments/assets/b4e17366-cd73-4ff9-aec9-8313aa744e01)

**Comment by eliasmoby** [comment]
I'm using f.port protocol but i cant get the altitude or some others sensors from the matek board, also if i would like to use sbus, i cant find sbus protocol just futaba sbus and futaba sbus2 on receiver tab of rf configurator. Its possible to use frsky sbus protocol? O just f.port.....?

**Comment by eliasmoby** [comment]
This afternoon i upgraded the rdmx to last version i got 1.0.7 and now the latest and all works great

Regards in advace

**Comment by eliasmoby** [comment]
Tks for the support

**Comment by egonl** [comment]
Go to Model > Telemetry and discover sensors first.

**Comment by eliasmoby** [comment]
Yes it works with the updated tdmx last version

Regards in advance
