### ISSUE TITLE
Custom CRSF telemetry missing GPS coordinates on EdgeTX

### ISSUE THREAD

**Issue by billiestrong** [rotorflight/rotorflight-lua-scripts#72]
### Behavior
GPS coordinates do not populate (sensor displays zero coordinates) when using custom CRSF telemetry on EdgeTX w/ Radiomaster TX16S. Observed at 2.1.0-RC1 on 3 November 2024 using Radiomaster TX16S running EdgeTX 2.10.5 Centurion.

### Example Code
See [this fork commit](https://github.com/billiestrong/rotorflight-lua-scripts/commit/79a6e67f14e8eb4ea98cf01a88d88ac42b6fcfa1) for a modified script version that results in correct GPS coordinate display on the system that originally exhibited this issue.

### Causes
This may be a similar issue to [the issue discussed in this openrcforums post](https://openrcforums.com/forum/viewtopic.php?t=11531). `UNIT_GPS_LONGITUDE` and `UNIT_GPS_LATITUDE` are not defined in lua, at least for this EdgeTX version.

Defining `UNIT_GPS_LONGITUDE` and `UNIT_GPS_LATITUDE` locally in [`decLatLong()`](https://github.com/rotorflight/rotorflight-lua-scripts/blob/6add88e39436c14e95d3e3ca97f5e209be6659ae/src/SCRIPTS/MIXES/rf2tlm.lua#L111) based on unit declarations in [EdgeTX source file `dataconstants.h`](https://github.com/EdgeTX/edgetx/blob/366df6080e915aa5ee76fe58e751aa013849f0e2/radio/src/dataconstants.h#L330) results in display of GPS coordinate values, though they are scaled up by a factor of 10.

The cause of the scaling change is unknown at the time of issue creation. Manually dividing the values by 10 corrects the fault. This scaling may require its own issue in [rotorflight-firmware](https://github.com/rotorflight/rotorflight-firmware).

**Comment by billiestrong** [comment]
Confirmed this behavior still occurs with hardware running ELRS 3.5.1.

**Comment by rotorflight** [comment]
Can you open PR on your commit. It seems to be the right way to fix this.

**Comment by billiestrong** [comment]
https://github.com/rotorflight/rotorflight-lua-scripts/pull/73

**Comment by billiestrong** [comment]
Closed with https://github.com/rotorflight/rotorflight-lua-scripts/pull/73
